spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/motr3x
    username: motr3x
    password: 1488
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
bot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}

